services:
  # Backend API & WebSocket Service (Express + Socket.io + Mongoose)
  - type: web
    name: youtube-backend
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DB_URL
        sync: false
      - key: PORT
        value: 5000

  # Frontend Web Service (Next.js)
  - type: web
    name: youtube-frontend
    runtime: node
    plan: free
    rootDir: yourtube
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: youtube-backend
          property: host
